name: Release

on:
  release:
    types: [published]

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    name: Create release artifacts
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Adjust version in manifest.json
        shell: bash
        run: |
          version="${{ github.event.release.tag_name }}"
          version="${version#v}"
          jq --arg version "$version" '.version = $version' \
            custom_components/*/manifest.json > tmp.json && \
            mv tmp.json custom_components/*/manifest.json

      - name: Create zip for release
        shell: bash
        run: |
          cd custom_components/*
          zip -r ../../release.zip .

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
